version: '3.8'

services:
  storytel-provider:
    build: .
    container_name: storytel-provider
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - abs_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/search?query=test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  abs_network:
    external: true
